### ISSUE TITLE
Create sub-phase tickets correctly

### ISSUE THREAD

**Issue by smood922** [greenloop-it-solutions/GL-CWManage-Tools#1]
In `https://github.com/greenloop-it-solutions/GL-CWManage-Tools/blob/main/ProjectTools/Create-ProjectWorkPlanFromCSV.ps1` tickets created with a second-level WBS code need to be created under the appropriate sub-phase (for instance ticket with wbs code 2.3.1 should be created under phase 2.3, not under phase 2).

**Comment by twilson-gl** [comment]
@smood922 Ticket creation under the appropriate sub-phase is now working as expected. There's logic in place to detect the length of a WBS code in order to determine which parent phase it belongs to.
