### ISSUE TITLE
Remove our Client ID

### ISSUE THREAD

**Issue by smood922** [greenloop-it-solutions/GL-CWManage-Tools#2]
https://github.com/greenloop-it-solutions/GL-CWManage-Tools/blob/80252d5b1275274294ea6bfbac9aefdcbeda0fda/ProjectTools/Add-WBSPrefixToProjectTickets.ps1#L18

Need to remove our Client ID and replace with logic to prompt for a Client ID.

**Comment by twilson-gl** [comment]
@smood922 I removed the Client ID and replaced it with a prompt
